### ISSUE TITLE
Annual Revenue Filter/Number of Employees Filter

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/site-selector#106]
The annual revenue filter and Number of Employees filter do not appear to be honored on the business tab. 

Repro steps: From the business tab-
- use the default address
-4 mile buffer
-input 100000 and 2000000 in the input boxes
- Click Search (magnifying glass)

Utilites Bus - 396,612,193

Repro steps for number of employees:

- use the default address
-4 mile buffer
-input 400 and 2000 in the input boxes
- Click Search  (magnifying glass)

Construction- 4920

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding We will fix this and include the fix in next sprint.

**Comment by lindsayking** [comment]
Adding a screen grab for reference:
![siteselectorissue106](https://cloud.githubusercontent.com/assets/4316336/6492499/db99c216-c268-11e4-8ffb-aed5d789f76d.png)

**Comment by LindsayThomas** [comment]
Expectation: 

The expectations of the application are as follows: 
A. Do location Search without any filters = Results returned are only location based
B. Do location Search with filters applied = Results returned are location based with filters applied on the results as well (only location base results that fit the filter should be visible).
C. Do location Search. Get results, then apply filters.

**Comment by lindsayking** [comment]
@NikkiGolding @LindsayThomas 

The second scenario listed above no longer applies because the location search must be executed before it is even possible to apply filters.  First and third scenarios work.

**Comment by LindsayThomas** [comment]
A and C still work. 
B is no longer an option
