### ISSUE TITLE
Increase the size of the text boxes for filter values on all tabs

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/site-selector#107]
It is hard to determine the value that you have but into the box

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding 
To resolve this issue we have increased the size of the text boxes for filter values. Please refer below image.
![text field](https://cloud.githubusercontent.com/assets/2959186/6214495/00dc0274-b61f-11e4-81bc-69ce6497d749.jpg)

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam  That looks better

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding 
We will provide this fix in next release.

**Comment by lindsayking** [comment]
@NikkiGolding   The text boxes for filter values have increased in size with version 1.4.  The image below shows the comparison between the latest version (left) and the released version (right).

![image](https://cloud.githubusercontent.com/assets/4316336/7424151/dbede352-ef52-11e4-9adc-86b18fe62c8d.png)



Do you think the size has increased enough in the latest version?

**Comment by LindsayThomas** [comment]
size updated per discussion with CT above . Looks good on LG\SG. Tablet and DT
