### ISSUE TITLE
Table columns are reversed on Property and Site information reports

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#110]
In the Property Information report, Neighborhood Information displays in the right column of the table.
In the Site Information report, Neighborhood Information displays in the left column of the table.

Display of the Neighborhood Information should be consistent between both reports.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We will fix this as a part of next delivery.

**Comment by lindsayking** [comment]
Verified with v1.4.
