### ISSUE TITLE
Multiple filters on the same field always default back to first filter

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#117]
@busbus @LindsayThomas 

Under <code>RegularFilterOptions</code>, if multiple filters use the same field, only the first filter is ever used in the application.  Clicking on other filters always activate the first.

For example, two filters using the same AQUISITION field:
```
RegularFilterOptionFields: [
                           {
                           DisplayText: "For Sale",
                           FieldName: "ACQUISITION",
                           FieldValue: "Sale"
                            }, {
                            DisplayText: "For Sale or Lease",
                           FieldName: "ACQUISITION",
                           FieldValue: "Sale or Lease"
                            }
                            ],
```

Show up in the application, 
![image](https://cloud.githubusercontent.com/assets/4316336/5910590/9d8c99ea-a570-11e4-97dc-f96c252fcf79.png)

But only the first, the "For Sale" option can be checked.  Checking on the "For Sale or Lease" option turns on the "For Sale" filter and leaves the "For Sale or Lease" option unchecked.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We will fix this as a part of next delivery.

**Comment by lindsayking** [comment]
Verified with v1.4.
