### ISSUE TITLE
Expand header to support more than 20 characters

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#119]
@lindsayking @NikkiGolding to consider for next release

![screen shot 2015-01-28 at 10 43 23 am](https://cloud.githubusercontent.com/assets/2379312/5959396/e76f98fa-a79b-11e4-891e-a601da2d1c6e.png)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We have resolved this issue. Please refer below screenshots and confirm the changes.
1. For single feature:
![header for single feature](https://cloud.githubusercontent.com/assets/2959186/6214794/47f3b966-b621-11e4-95d1-8afd368a9101.jpg)
2. For multiple features:
![header for multiple features](https://cloud.githubusercontent.com/assets/2959186/6214803/5662b65a-b621-11e4-9438-f29f643c2a15.jpg)

**Comment by LindsayThomas** [comment]
@ScottOppmann @NikkiGolding  Thoughts?

**Comment by NikkiGolding** [comment]
@LindsayThomas Looks good to me. Let CT know we want to implement if you are in agreement

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Please proceed with this implementation.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
great

**Comment by lindsayking** [comment]
Verified with v1.4.
