### ISSUE TITLE
 ShowNullValueAs: "N/A" isn't work for the distance property 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#120]
// Set string value to be shown for null or blank values
        ShowNullValueAs: "N/A",

The comment implies that NULL will appear as N\A if it is a string. 

Have we programmed the application to do this for integers? 

This is important for "site information" and "property information" when Distance to infrastructure is referenced. 

{
                                DisplayText: "Distance to Sewer (Mi):",
                                FieldName: "DISTSEWER"
                            },

@NikkiGolding @lindsayking To decide for next release

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas The application displays "NA" wherever attribute parameters are NULL irrespective of data type. We analyzed and found that "NA" is not getting displayed at few places. We have fixed this and will include this fix in the next release.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam  Great. 

Note for LT- Reported by customer.

**Comment by lindsayking** [comment]
Verified with v1.4.  

@LindsayThomas 
I experimented with different strings in the <code>ShowNullValueAs</code> parameter and they appeared correctly in the app for different attributes (included DISTSEWER in testing and confirmed string displayed correctly).
