### ISSUE TITLE
Copyright Credits from Service not webmap

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#121]
When a webmap is printed to the report. The Credits in the bottom right hand are coming from the Copyright text of the service. For Example 
http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer
Copyright Text: Sources: Esri, HERE, DeLorme, USGS, Intermap, increment P Corp., NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, MapmyIndia, © OpenStreetMap contributors, and the GIS User Community 

However, if you view this server and the specific area of the feature printed. The webmap has unique credits on each tile.

@lindsayking @NikkiGolding consider for next release

**Comment by lindsayking** [comment]
This is configurable in the config.  <code>ShowMapAttribution: true</code>
