### ISSUE TITLE
App not honoring custom attribute popups

### ISSUE THREAD

**Issue by busbus** [Esri/site-selector#122]
Webmap popup: 

![webmapopup](https://cloud.githubusercontent.com/assets/5614261/6009632/5ac0da16-aae0-11e4-9883-e263348cbe82.png)

Site Selector popup:

![ssapppopup](https://cloud.githubusercontent.com/assets/5614261/6009637/63e2b830-aae0-11e4-9d90-a0bf9a603720.png)

**Comment by CTLocalGovTeam** [comment]
@lindsayking  We will implement this and deliver in next release

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We have a question while implementing custom pop-ups.

Application honors the date format from application configuration (tag name: DatePattern). Should we honor date format from popup configuration or from the application configuration file? If we decide to honor the format from popup configuration then we will remove the config tag DatePattern. 

Please suggest.

**Comment by lindsayking** [comment]
@CTLocalGovTeam Please honor the popup configuration from the webmap and remove the DatePattern tag from the config.js.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We have made the suggested changes and removed the DatePattern tag from config.js. We will provide this fix in next release.

**Comment by lindsayking** [comment]
Verified with v1.4.
