### ISSUE TITLE
App not honoring attribute settings from webmap

### ISSUE THREAD

**Issue by busbus** [Esri/site-selector#123]
Webmap (0 decimal places displayed): 

![webmaoppopup](https://cloud.githubusercontent.com/assets/5614261/6083372/f0a20db2-addc-11e4-9d7f-23b9e5b22047.png)

Site Selector: 

![2-6-2015 8-44-30 am](https://cloud.githubusercontent.com/assets/5614261/6083384/0308beba-addd-11e4-89e3-93e25c3959d3.png)

**Comment by lindsayking** [comment]
It looks like this is related to #57.  This behavior might have been my mistake.  I misunderstood the solution to #57, which I think was to add two decimal places to number values in the popup.

**Comment by busbus** [comment]
I think that if someone authors a well-designed webmap they feel confused when they see it differently in the site selector app.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will revert to Webmap popup configuration

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We have implemented this change and will provide it in next release.

**Comment by lindsayking** [comment]
Verified in v1.4.
