### ISSUE TITLE
Enhancement Request - add the ability to pass the ID, Address, etc. into the app URL

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/site-selector#124]
As a 3rd party system, form, webpage, etc., I would like to add a pre-defined search item into the app.

Something like this - http://localhost/site-selector-development/?Address=1200 Hidden Spring Dr, Naperville, Illinois, 60540

**Comment by busbus** [comment]
This is an enhancement need for the Comparable Finder, most current comparable applications in the marketplace have tie ins/tie backs into the assessment systems.  I can provide detailed information regarding this enhancement request.
