### ISSUE TITLE
Scrolling does not happen when the Property Information has a lot of features. 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#125]
Scrolling does not happen when the Property Information has a lot of features. 

Repo Steps:
Go to http://tryitlive.arcgis.com/SiteSelectorIL/ on an iPad 
Search default building / Select first Default Address
Select Chucky Restaurant
You should see Property Information and Neighborhood Information in the panel
Property Information doesn't have scrolling built in. 
User cannot scroll through all the property information
User cannot see Neighborhood Information
Please add scrolling Support in this area. 

If you look at the another configuration with less default Property Information you will not see this issue ( For Example: http://tryitlive.arcgis.com/SiteSelector/  ) 

I think it would make sense for the whole panel to scroll.

**Comment by CTLocalGovTeam** [comment]
To resolve this issue we have made the entire panel scrollable for Buildings and Sites. Please refer below image and confirm the changes.
![scrollable info](https://cloud.githubusercontent.com/assets/2959186/6265150/ee87c6f6-b850-11e4-83ae-7221c354bdbd.jpg)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
Awaiting for your feedback.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam please implement.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We shall deliver this in the next release.

**Comment by lindsayking** [comment]
Verified on v1.4.

@LindsayThomas 
Tested with the list of attributes from the try it live.  The whole panel now scrolls, and it is a much better experience on an iPad.
