### ISSUE TITLE
Investigate where enrichment information is located now

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#126]
We need to investigate where the demographic/enrichment information is located now.  Fully rolled into AGOL at this point?

@LindsayThomas

**Comment by NikkiGolding** [comment]
@lindsayking Where are we on this?

**Comment by lindsayking** [comment]
@LindsayThomas and I talked with geoenrichment team.  Although the way we have been accessing the geoenrichment service is not wrong, we were told we could use authentication method in http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r30000009z000000 for the geoenrichment service.

**Comment by LindsayThomas** [comment]
@lindsayking @NikkiGolding We have updated information on this. I am closed this issue and opening a new one with all the details.
