### ISSUE TITLE
Report Title parameter for SiteSelectorPDFGen tool is overwritten by DisplayText from config.js

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#128]
The optional Report Title input parameter for the SiteSelectorPDFGen tool is not honored. Instead, the report title is controlled using the <code>DisplayText</code> in the config.js.

If a user indicates a custom Report Title when publishing the SiteSelectorPDFGen tool, that title is overwritten by whatever is indicated by the <code>DisplayText</code> in the config.js.

#112

**Comment by CTLocalGovTeam** [comment]
This is the intended design. The `DisplayOptionTitle` parameter is used to display title in pdf report. The app always sends this value to the gp service.

```javascript
          DownloadSettings: [
                        {
                            DisplayOptionTitle: "Property Information",
```

**Comment by lindsayking** [comment]
Closing this issue.  We understand now that the parameter is required on the UI even if its input is overwritten by the content of the config.js.
