### ISSUE TITLE
Update app to use layer name from the webmap, not the service

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#129]
Related to same changes being made for Live Work Locate:  https://github.com/Esri/live-work-locate/issues/118

**Comment by lindsayking** [comment]
Updated the issue: The app needs to be updated to use only the layer name from the webmap. We want to remove any dependency on the layer id and remove the QueryLayerId from the config.js.

**Comment by NikkiGolding** [comment]
@lindsayking Please update this with the approach we discussed this morning.

**Comment by lindsayking** [comment]
Revised approach:  We want to use a combination of the layer name and the layerID. The layer name needs to be read from the webmap. The index number should come from the service (e.g. the "0" at the end of http://50.18.115.76:6080/arcgis/rest/services/WaterAccess/MapServer/0).

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will follow the approach explained in [issue 99 of Configurable Lcoator](https://github.com/Esri/configurable-locator/issues/99) for Layer name and index.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We shall deliver this in the next release.

**Comment by lindsayking** [comment]
Verified in v1.4.
