### ISSUE TITLE
SiteSelectorPDFGen Attachment List parameter - needed in the tool UI?

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#131]
According to #113, the Attachments List parameter is needed in the tool's UI.  But since it is used by the application to send the list of attachments, would the user publishing the GP tool be able to modify the list of attachments?  Or will it always be overwritten by what the application sends? 

If the user is unable to modify the attachment list when they run the GP tool, we should hide this parameter from the tool's UI.

**Comment by lindsayking** [comment]
To add a little more information on this, I published a [test version of the tool](http://50.18.115.76:6080/arcgis/rest/services/SStestDev/GeneratePDFAttTest/GPServer/SiteSelectorPDFGen), passing in a URL to a test .PNG image in the Attachment List parameter.  When I configured the app to use this test version of the tool and I used the app to download reports, the reports reflected the image attachment on the feature, but did not include the test .PNG image that was referenced in the Attachment List parameter when the tool was published.

**Comment by CTLocalGovTeam** [comment]
@lindsayking,
Can you please describe in brief how we can accomplish hiding a parameter in the gptool UI and still be able to view that parameter as a user defined input that the application can use to send data through in the geoprocessing service?
When we build a geoprocessing tool, we were not able to locate any setting whereby we can designate a parameter that is optional and settings to hide its visibility in the tool UI. 
Any help is greatly appreciated.

**Comment by lindsayking** [comment]
Closing this issue. We understand now that the parameter must be exposed in the UI.
