### ISSUE TITLE
Reduce and minimize use of global variables in dojo global variable

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#133]
Related to https://github.com/Esri/configurable-locator/issues/126.  

Code needs to be reviewed and modified to reduce, minimize and limit the number of global variables into the dojo global variable. This work will have the benefit of easier code maintenance over time.  This should be done throughout the codebase.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will follow the approach mentioned below to remove dojo level variables from codebase.

In bootStrapper.js we have created a new object as :
```javascript
     appGlobals = {};
     // assign  config data in appGlobals variable
     appGlobals.configData = config;
     // assign object to store variables for sharing in appGlobals variable
     appGlobals.shareOptions = {};
```
Eg. 
`dojo.configData.ProxyUrl` will be accessed as `appGlobals.configData.ProxyUrl`
and 
`dojo.selectedBasemapIndex` will be accessed as `appGlobals.shareOptions.selectedBasemapIndex`

Please confirm.

**Comment by lindsayking** [comment]
@MikeTschudi  What are your thoughts on this approach?

**Comment by CTLocalGovTeam** [comment]
@Lindsay K 
We are awaiting your confirmation on the approach outlined in the previous comment.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam please use the approach mentioned above. 

This issue exists in more than dojo.configData.ProxyUrl and dojo.selectedBasemapIndex.  
Is the intention to fix in all other places as well?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We would be using the same approach as mentioned above to remove all dojo level variables.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Great. Just wanted to make sure.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We shall deliver this in next release

**Comment by lindsayking** [comment]
@MikeTschudi  Are you able to validate that this issue has been fixed?

**Comment by MikeTschudi** [comment]
Yes, all globals appear to have been moved from the 'dojo' global variable into an app-specific 'appGlobals' global variable.

**Comment by lindsayking** [comment]
Excellent, thank you @MikeTschudi.  Closing this issue.
