### ISSUE TITLE
Map attribution is not updated when basemap switches

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#135]
@CTLocalGovTeam  -  The map attribution does not update when the basemap switches.  It appears instead to always display the copyright text for the default webmap only.

For example, the default basemap for http://tryitlive.arcgis.com/SiteSelector/ is the National Geographic basemap, yet when the basemap is switched, the National Geographic copyright text remains.  See the image below in which the basemap has been switched to Topographic basemap:

![image](https://cloud.githubusercontent.com/assets/4316336/6494928/3a3bf3e6-c27a-11e4-906e-c838b28f4b40.png)

**Comment by CTLocalGovTeam** [comment]
@lindsayking  We are investigating this issue.

**Comment by lindsayking** [comment]
Related to https://github.com/Esri/environmental-impact/issues/177

**Comment by lindsayking** [comment]
Verified with v1.4.
