### ISSUE TITLE
Update app to use layer name from the webmap, not the service

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#136]
@CTLocalGovTeam 

We want to use a combination of the layer name and the layerID. The layer name needs to be read from the webmap. The index number should come from the service (e.g. the "0" at the end of http://50.18.115.76:6080/arcgis/rest/services/WaterAccess/MapServer/0).

Please use the same approach for this issue as for https://github.com/Esri/configurable-locator/issues/99.

**Comment by CTLocalGovTeam** [comment]
@lindsayking This is same as #129.

**Comment by lindsayking** [comment]
Is duplicate.  Closing.
