### ISSUE TITLE
Console Error in application

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#137]
Console error issue: variable used to generate the URL is undefined:

![fidder](https://cloud.githubusercontent.com/assets/2379312/6515010/d06a795c-c354-11e4-81da-e5fd056a76a7.png)

Repro Issue:
Go to the application: http://tryitlive.arcgis.com/SiteSelectorIL
Open developer tools console
Search for 1100 Hidden Spring Dr, Naperville, Illinois, 60540
then you see the error. 

(To repro this issue locally please use the ConfigLG.js file)

**Comment by LindsayThomas** [comment]
@lindsayking @NikkiGolding  FYI

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  We will fix this and deliver in the next release.

**Comment by lindsayking** [comment]
@LindsayThomas   I am no longer able to reproduce this issue using http://50.18.115.76/SiteSelectorLG/ and the repro steps you provided above.

**Comment by LindsayThomas** [comment]
verified on LG.
