### ISSUE TITLE
Filter Options Clarification

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/site-selector#139]
@CTLocalGovTeam Please provide clarity on the filter options in the configuration file. 

Filter Range
Regular Filter
Additional FIlter Options

Are their specific controls tied to each? eg: Filter enables a from/to ; Regular is a radio button
 How do these different options affect the UI?

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding 

Filter Range - Text box controls for 'From' and 'To' are displayed for filter ranges configured under FilterRangeFields 
 
Regular Filter - Checkboxes are displayed for filters configured under FilterOptionFields   

Additional Filter Options - Checkboxes are displayed for filters configured under AdditionalFilterOptions

**Comment by NikkiGolding** [comment]
@lindsayking Please add these to the doc for additional configuration for the April release.

**Comment by lindsayking** [comment]
@NikkiGolding 
https://github.com/ArcGIS/arcgis-solutions-website/issues/1832 has been created to making this change in the doc.
