### ISSUE TITLE
The apply filter icon will be enabled after user selects any filter option

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#143]
Per Filter Change Call on 3/23/2015

The apply filter icon will be enabled after user selects any filter option

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas , @NikkiGolding 

On application load, the filters will be disabled as shown in the below mockup
![02](https://cloud.githubusercontent.com/assets/2959186/6866230/376733e0-d49c-11e4-8aa5-bb33eadd8278.png)

Mockups for #141, #142 
![image](https://cloud.githubusercontent.com/assets/2959186/6866165/9a834582-d49b-11e4-803b-a2eb0d1823ed.png)

Mockups for #150 
![image](https://cloud.githubusercontent.com/assets/2959186/6866244/47ba1b0e-d49c-11e4-9004-fc8e35728b88.png)

Mockups for #143, #148 
![image](https://cloud.githubusercontent.com/assets/2959186/6866266/7e497426-d49c-11e4-9cad-9c6deefff79c.png)

Mockups for #144, #151 
![image](https://cloud.githubusercontent.com/assets/2959186/6866273/8d41a4da-d49c-11e4-80b7-0d52cfcb2dd4.png)

#145 - Ok, we will provide tooltips.

#149 - We are already maintaining consistency in the Font Family and Size in the application. We will ensure that “Filter” text is padded and aligned correctly.

**Comment by NikkiGolding** [comment]
@ScottOppmann Thoughts?

**Comment by ScottOppmann** [comment]
The new UI looks good and flow seems reasonable.   May be the screenshots, but the the clear filter button icon is very subtle.  Is there another icon we could use to make it more obvious to users?

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam Please move forward with these changes. Per Scott's note, please explore making the clear filter graphic  a bit more apparent.

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding, @ScottOppmann We have designed following options for clear filter graphic. Could you please confirm on one of these ?

Options for Clear Filter
![resetfilteroptions](https://cloud.githubusercontent.com/assets/2959186/6981821/b625b876-da25-11e4-8299-76f3335af4b0.png)


Option 6 - Illustrated
![image](https://cloud.githubusercontent.com/assets/2959186/6981880/f8b287a4-da26-11e4-9bc7-c15b7eefff07.png)

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam Let's go with number 6.

**Comment by LindsayThomas** [comment]
-We are using option 6 
-Apply filter icon will be enabled after user selects any filter option
