### ISSUE TITLE
Filter error message logic

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#147]
Per Filter Change Call on 3/23/2015

When filters are active, if user changes any filter options and changes buffer distance or address without clicking on apply filter, then    
a.	All filters are honored if there are no validation errors for any of the filters
b.	If any filter fails validation, then alert messages will be displayed to guide user to correct inputs and results panel will remain unchanged

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas If any of the filter validations fail then the results panel will remain unchanged. This will require buffer distance and address to be reset to earlier values so that the results shown are in sync with the buffer distance and address.

**Comment by LindsayThomas** [comment]
@NikkiGolding This okay with you?

**Comment by NikkiGolding** [comment]
@LindsayThomas  Yes.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Okay, please proceed with fix
