### ISSUE TITLE
NLS\<language>\localizedstring.js  is not being loaded in app

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#153]
Dojo is detecting the native browser language
However, the localizedstring.js isn't being loaded in the application 

@CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We will fix this as a part of next release.

**Comment by LindsayThomas** [comment]
Native French FF. Localized String is being loaded\detected. 
As expected, Dojo is loading in French in the native browser as well.
