### ISSUE TITLE
Add support for PDF and other attachment types

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/site-selector#155]
Currently, the application only supports photos stored as attachments.  Users would like to associate PDFs and other document types as related information to the site.  

@lindsayking @LindsayThomas @NikkiGolding
<span><b>Salesforce ID:</b> ENH-000087192</span><br/>

**Comment by LindsayThomas** [comment]
@ScottOppmann @lindsayking @NikkiGolding 

I've asked Support to log this issue. That way we can communicate with the customer what direction we are going to take with this request. (If needed we will link this issue later)

Note: PDF’s are not currently supported in the application. 
The workaround would be to convert the image into a supported format. 
Currently, we support Bitmaps, PNG,  and JPEG’s . 
The PDF the customer would like to support is an IMAGE pdf not a pdf document.

**Comment by LindsayThomas** [comment]
To me this discussion isn't about PDF's as image attachments but rather how does the application handle other attachment types. There is interest in the user community about using this as a way to get additional information into the application.

**Comment by lindsayking** [comment]
@CTLocalGovTeam  Please provide screenshots of how you plan to implement this change in the application.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 

A default thumbnail will be displayed for all non-image file types. The size of the non-image thumbnail will be same as the image thumbnail. Please refer the screenshots below. Any change will involve additional effort for layout adjustments. Please confirm.

![image](https://cloud.githubusercontent.com/assets/2959186/9683156/29d23b04-532b-11e5-8244-8dd305c6bccd.png)

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam What is the level of effort to adjust the style/css to adjust the thumbnail for non-image file types.

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding 

We can retain the thumbnail size in both views and change the image according to theme color. This can be done with minimal code changes. 

Please confirm the screenshots for blue theme.

![image](https://cloud.githubusercontent.com/assets/2959186/9761628/a231489e-571b-11e5-8951-2dc55c12c048.png)

**Comment by NikkiGolding** [comment]
@ScottOppmann  Looks ok. to me. Thoughts?

**Comment by lindsayking** [comment]
http://50.18.115.76/SiteSelector2.3wAttachments/ has been stood up with various forms of attachments.  If you search within a few miles of the default search address, buildings have examples of jpg, ppt and txt attachments.  Sites also have an example of pdf attachments.

**Comment by lindsayking** [comment]
Downloading Property/Site Information reports fails with different attachment types.

Steps to repro:
Using http://50.18.115.76/SiteSelector2.3wAttachments/ as an example,
1)  On the Buildings tab, search using the default address and a buffer distance of about 2 miles
2) On the results panel, click on one of the results that have no attachments, then download the property information report.  Note that the download succeeds.
3) Back on the results panel, select one of the results with a non-image attachment (e.g. .txt, .pdf or .ppt), then download the property information report.  Note that the download fails "Unable to complete operation".

The same behavior can be seen on the Site tab when searching using the default address.  The University Town Center - Phase II Site feature has a .pdf attachment, and the download fails for this feature.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We are able to reproduce this. This is occurring because the property information reports are designed to include the image attachments for a property in the pdf report. Image attachments are sent as a list of attachment URLs to the geoprocessing service. As a consequence, it is trying to add the non-image attachments to the pdf too and unable to generate the report.

We can resolve this by code changes on either the application side or on the geoprocessing service, or both. Please let us know your preference.

1. Update the geoprocessing service to ignore non-image attachments
2. Update the application code base to filter and send only URLs to attachments of image types
3. Update both app and gpservice to ignore non-image attachments

**Comment by lindsayking** [comment]
@CTLocalGovTeam   We are thinking option 2 above would be the best option.  Can you provide us additional information regarding the level of effort or risk involved in each of the three options you describe above?

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
In all three cases the level of effort and risk involved is minor. 
Option 2 is the most straightforward, since there is logic already to identify non-image attachments to display the attachment icon in the app. The same logic can be extended to send only image types to geoprocessing service.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   As we discussed on our call, please proceed with option 2.

**Comment by lindsayking** [comment]
Verified with v1.8 - UAT Bug Fix.  Was able to successfully download property/site information reports for features with various attachment types: pdf, image, txt, ppt.  Only image attachments displayed in the reports.
