### ISSUE TITLE
Third Party Commerical Data Sources

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/site-selector#156]
Develop an integration pattern for third party commercial data sources used for the site and building layers.    Look at national data sources like CoStar and see if we can determine a pattern that might be usable by many of the regional data providers.  Should also talk with Content Team to see if they have made any progress partnering with CoStar and getting their data added as a premium service.

FYI - @NikkiGolding @lindsayking @LindsayThomas

**Comment by ScottOppmann** [comment]
Investigate the use of FastFacility.

**Comment by NikkiGolding** [comment]
Xcelligent
CoStar/
Loopnet
