### ISSUE TITLE
Null Values represented on Business Tab

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/site-selector#157]
@lindsayking 

In the version 1.3 Try it Live apps  on the business tab, when GeoEnrichment is run it returns null values for Business, Employees, and Revenue. Please validate that this is not a configuration issue on our side. Please also check this first when validating the 1.4 drop. 

@LindsayThomas  @ScottOppmann  FYI.

**Comment by lindsayking** [comment]
@NikkiGolding  This issue has been fixed on the [try it live version of the State app](http://tryitlive.arcgis.com/SiteSelector/) (using the method described in issue #158).  It required a configuration change on our side, and the 1.4 drop requires the same configuration change.

I will update this thread once the configuration files in the repo have been updated with this change.

**Comment by LindsayThomas** [comment]
updated LG and SG config
