### ISSUE TITLE
Update Character limit on community drop-down

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#159]
@CTLocalGovTeam 

When the application is configured to use the COUNTYNAME field that contains full names for counties (rather than four-letter abbreviations) the drop-down on the Communities tab becomes unusable:

![image](https://cloud.githubusercontent.com/assets/4316336/8046525/70df3b6c-0df0-11e5-92b8-62ee1c1ecbf2.png)

http://54.176.227.230/SiteSelectorIssue159 has been stood up with this behavior.  The communities tab is pointing to http://50.18.115.76:6080/arcgis/rest/services/SStestDev/SiteSelectorMuniFix/MapServer/2, which has been published with an additional COUNTYNAME field that includes full names for each county.  

```
FilterLayer: {
                        Title: "SiteSelectorCountyName - Municipalities",
                        QueryLayerId: "2",
                        FilterFieldName: "COUNTYNAME",
                        OutFields: ["COUNTYNAME"]
                    },
```

When the application is configured to use this field, the drop-down becomes unusable.  Is there a character limit that prevents the application from being able to handle full county names?

For comparison, the drop-down works as expected for http://tryitlive.arcgis.com/SiteSelector/, which uses the four-letter abbreviation for each county.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
There is no character limit in place. This behavior is occurring due to an issue with the way the app is querying countynames and populating the dropdown. It is actually passing the complete text `"["COUNTYNAME"]"` (including the square brackets and quotes) as the outfield parameter to the query, whereas it should just pass `COUNTYNAME` as the outfield parameter to the query. 

We have seen that this works only when you configure the outfield which is the same as default display field configured in the layer at REST. Hence, it is working at http://tryitlive.arcgis.com/SiteSelector/ because the configured outfield (COUNTY) is the same as default display field (COUNTY) for that layer.

To fix this, the config file needs to be updated to use the FilterFieldName as the query outfield and remove the `OutFields` parameter from the config file as it would no longer be required.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Can you please provide a sample of what this fix would look like in the config file?

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
Here is how the config file would look like

![image](https://cloud.githubusercontent.com/assets/2959186/8496575/e97f107c-2193-11e5-9e62-c447c1e77926.png)

**Comment by LindsayThomas** [comment]
@lindsayking is accessing the fix. 

LK if it works then can you add this to the Esri Post-UC Release milestone?

**Comment by lindsayking** [comment]
@CTLocalGovTeam 

http://50.18.115.76/SiteSelectorIssues/ has been configured with the changes described above.  This is what the config looks like:
```
FilterLayer: {
                        Title: "Municipalities",
                        QueryLayerId: "2",
                        FilterFieldName: "COUNTYNAME"
                    },
```

But I am still seeing the same behavior in the community tab's drop-down:
![image](https://cloud.githubusercontent.com/assets/4316336/8662687/3aa96dfe-2977-11e5-87b5-dea40f2e7858.png)


Are any other changes needed in the config file?

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
Just the config change wont fix it. This also needs a code change to implement the fix.

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam Please submit the change with the next code drop.

**Comment by lindsayking** [comment]
Validated with v2.1.  With the app configured to filter on the COUNTYNAME field (full county names) rather than the four-letter county abbreviations, the full county names display correctly in the community drop-down.
```
Name: "Communities",
                Enabled: true,
                EnableSearch: true,
                EnableDropdown: true,
                FilterSettings: {
                    StandardGeographyQuery: {
                        LocatorDefaultAddress: "Baltimore, MD",
                        QueryField: "geographyQuery",
                        SourceCountry: "US",
                        FeatureLimit: 10
                    },
                    FilterLayer: {
                        Title: "Municipalities",
                        QueryLayerId: "2",
                        FilterFieldName: "COUNTYNAME"
                    },
```

![image](https://cloud.githubusercontent.com/assets/4316336/10296912/1787a334-6b82-11e5-9912-67cb93e1fb3e.png)
