### ISSUE TITLE
If layer’s visibility is turned off in webmap, then related search functionality still works. Applicable to Buildings, Sites and Community tabs.

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/site-selector#160]
@lindsayking 
The buildings tab is fully functional even if the building layer’s visibility is turned off in webmap. User can still perform search by address, apply filters etc., but buildings are not visible on map. 

It is expected that if building layer is turned off in webmap, then app should not display any building results. Filters should be disabled. If user performs an address search, it should only display the buffer graphic. No results should be displayed for buildings in the result panel.

**Comment by LindsayThomas** [comment]
No Action Required.  As Known Limit\As Designed
