### ISSUE TITLE
When results are sorted by Area field and shared by email, the shared link displays a different set of results.

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/site-selector#161]
@lindsayking 
This is reproducible in both Buildings and Sites tab.
Steps to reproduce.
1. Perform an address search to display results
2. Sort the results by Area field and share via email
3. Open shared link and notice that app displays a totally different set of results

This is reproducible only when sorted by Area field, other fields work fine.

**Comment by lindsayking** [comment]
Verified with v2.1.
