### ISSUE TITLE
If basemap group does not contain any basemaps, then basemap switcher is still displayed in application.

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/site-selector#163]
@lindsayking 
When a basemap group is configured that does not contain any basemaps, application displays an error message (no basemap found) and displays the basemap switcher without any thumbnail. 

In such case, the basemap switcher should not be displayed.

**Comment by LindsayThomas** [comment]
reported by CT

**Comment by LindsayThomas** [comment]
Also, if the basemap group title and \ or owner  is empty or has an invalid input then it should also how the same behaviour (the basemap switcher should not be displayed.)

 BasemapGroupTitle: "",
 // Specify the user name of owner of the group that contains basemaps
 BasemapGroupOwner: "",

**Comment by lindsayking** [comment]
@CTLocalGovTeam 

With v2.1, I am no longer seeing the basemap switcher when a basemap group is used that does not contain any basemaps.  This is the correct behavior.

However, in reference to @LindsayThomas's comment above, I also should not see the basemap switcher if the BasemapGroupTitle or BasemapGroupOwner settings are empty or invalid.  A test app has been stood up at http://50.18.115.76/SiteSelector2.1 with the BasemapGroupTitle and BasemapGroupOwner parameters empty.  I am still seeing a basemap switcher in this scenario, but it is not functional.  This is not the correct behavior.  The basemap switcher should not display in this situation.

**Comment by CTLocalGovTeam** [comment]
We will provide the fix in next release.

**Comment by lindsayking** [comment]
Verified with v1.6.
