### ISSUE TITLE
IE8  popup does not display correctly: If popup content does not fit within the popup window, the text actually extends below the bottom of the popup, and the user cannot scroll the popup.

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#165]
Note: this is a bounce back. Older versions did not have this issue.

If popup content does not fit within the popup window, the text actually extends below the bottom of the popup, and the user cannot scroll the popup.

![siteie8](https://cloud.githubusercontent.com/assets/2379312/8255059/446fa4ee-166b-11e5-9270-695890dd60d2.png)

**Comment by lindsayking** [comment]
Known issue.  No longer supporting IE8.
