### ISSUE TITLE
Firefox: In some cases the tabbed browser display is below the header bar

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#166]
![fftab](https://cloud.githubusercontent.com/assets/2379312/8255168/f4e59e50-166b-11e5-9d13-a1fda95dac91.jpg)

@jmhauck Could you please add repro steps to get this behavior in Firefox? (please note the FF version as well)

**Comment by jmhauck** [comment]
Firefox 38.0.5

This is a portrait display with a widescreen monitor…the app is maximized. Looked fine in landscape with the same type of widescreen monitor. Same issue did not occur with chrome on the same display.

**Comment by LindsayThomas** [comment]
(Lt has seen this in other cases as well. I don't have a repro for mine yet.
