### ISSUE TITLE
Site\Building Information printed map, consider making the selected feature clearer. 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#167]
In the map at the top of the pdf reprorts, the active feature is selected but it actually seems to “pop” the least out of all points displayed.

Consider making it clearer by using a different selection\highlight option

**Comment by lindsayking** [comment]
Ripple highlighting the feature instead seems to overlap it and gray it out:
![image](https://cloud.githubusercontent.com/assets/4316336/8661119/32228380-296a-11e5-99f5-2387be7a127b.png)

**Comment by lindsayking** [comment]
@NikkiGolding @ScottOppmann @LindsayThomas 

In the config.js, we have the ability to change the size and the outline color of the "ripple", but not its fill color or transparency.  As you can see in the screenshot above, there appears to be some transparent gray shading within the ripple circle, but that shading is not configurable in the config.js.

**Comment by NikkiGolding** [comment]
@lindsayking  I think at this point, my suggestion is to change the color of the halo around the feature to draw attention to it. I dont think we need to add another config parameter to support a change in ripple color for .pdfs.
