### ISSUE TITLE
The map should update to reflect search

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#169]
Currently, if you filter sites or buildings down to 11 features then, you will not see the map update. 

this is particularly evident in the state configuration.

**Comment by LindsayThomas** [comment]
Searching for Sites only shows Sites on map 
Searching for Building only shows Buildings on map 
Map updates to reflect filters

**Comment by CTLocalGovTeam** [comment]
@lindsayking, @LindsayThomas 

Can you please describe what is expected from "map should update to reflect applied filters". Is it that the map should only display features that are included in the filter? If yes, do we display all features when app loads, or we display features only when user applies a filter?

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam  The maps should render all information unless a filter is applied. Once a filter is applied the map should only show the results of the filter.

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding 

To implement this feature of showing only filtered features on map, we are thinking of using a separate graphics layer for this purpose. 

* The app initializes the map based on the webmap id, i.e. all layers are displayed when the app loads up. 
* When Sites tab is open, it will display only Sites layer and hide the Buildings layer and vice versa. Any layers other than Sites and Buildings present in the webmap will be displayed in all the tabs.
* Communities and Business tabs will display all layers present in the webmap including the Sites and Building layers.
* When the app loads, and no filters are applied yet, all features are displayed for Sites and Buildings in their respective tabs.
* When a filter is applied, either by buffer or attributes, the layer's display will be turned off and the results of the filter will be displayed on a separate graphics layer. This graphic layer will always display only the results of the filter.
* User can click features added to graphics layer to view their popups.

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam  What is the benefit of using a graphics layer vs. passing queries to the feature service directly and rendering the results from the feature service?

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding 

We cannot use the feature layer that is added to map directly because it is always initialized in on-demand mode i.e., it updates on map pan and zoom. The webmap may also contain Sites and Building layers as dynamic map services or even query enabled tiled services. Hence, a separate graphic layer showing only the results of the queries is suggested as a unified way to support all types of services.

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam  Please proceed with the above approach using the graphics layer.

**Comment by CTLocalGovTeam** [comment]
This will be implemented in next release.

**Comment by lindsayking** [comment]
@NikkiGolding @ScottOppmann @LindsayThomas - With v1.6, the map does update the reflect filters as we would expect.

However, if the search and applied filters return back 36 results, for example, only 10 results show on the map.  These 10 correspond with the 10 that are currently visible on the first page of results.  When you paginate to the next 10 results, the map then updates to show those 10 features.  I like this behavior, but wanted to confirm this is matches the design we had in mind.

**Comment by NikkiGolding** [comment]
@lindsayking Will you provide a link to the deployed app?

**Comment by lindsayking** [comment]
@NikkiGolding   http://50.18.115.76/SiteSelector2.2/

**Comment by lindsayking** [comment]
@CTLocalGovTeam 

If more than ten results are returned from the search/filters, please display all results on the map.  Do not limit the features on the map to only list the first ten listed on the results panel due to pagination.  We want to see all results from the search and filters on the map.

For example, if on the buildings tab, and we perform a search and apply filters, returning 25 buildings that meet the criteria, we want to see all 25 buildings on the map.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
Do we display all features from the applied filter? Often this may lead to a large number of graphics added to the map (hundreds or even thousands) and make the app sluggish. 
Legacy browsers like IE8, IE9 become sluggish with approximately 500 - 2000 features. Modern browsers have a better graphic rendering engine and are responsive with up to even 5000 graphic features added on map. 

You can view the performance of large number of points added to map on this [esri demo app](http://servicesbeta.esri.com/demos/graphics-performance/points.html) in various browsers. Please select picture marker symbol in the demo.

**Comment by NikkiGolding** [comment]
@ScottOppmann @LindsayThomas  I don't anticpate a search that warrants a result set of 500 + features. Thoughts?

**Comment by ScottOppmann** [comment]
I agree.

Sent from Scott's iPhone
909-728-7082

On Oct 27, 2015, at 11:29 AM, Nikki Golding <notifications@github.com<mailto:notifications@github.com>> wrote:


@ScottOppmann<https://github.com/ScottOppmann> @LindsayThomas<https://github.com/LindsayThomas> I don't anticpate a search that warrants a result set of 500 + features. Thoughts?

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam  Please proceed with the requested change.

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding  
The current filtering behavior of the app is to fetch only ids for a query and split them into batches to query for pagination. This allowed us to query only the first batch of 10 features and display them on map and query again for the next 10 on the next page. This also had the advantage that the result count of features was accurate even if large number of features (>1000 or server limit) satisfied a query. For e.g., user increased the buffer distance all the way up to 50 miles. Users had the ability to page through all results for such large queries or jumping to the last page by specifying the page number. However, adding large number of features to map is not desirable for performance reasons, especially on IE browsers.

We are proposing the following approach to display all features from filters on the map.   
* When a filter is applied or buffer distance is changed, don't get just the ids, instead get all features that satisfy the query and directly add them to map as graphics
* The number of features that can be queried and displayed is determined by the server limit, usually it is 1000 features
* The count of features will always be 1000 or whatever is the server limit, if a larger number of features satisfy the filter  
![image](https://cloud.githubusercontent.com/assets/2959186/10815073/b4704068-7e4f-11e5-9b40-656fdd05c920.png)
* This will not affect the performance of the app
* Users can always increase the server limit to return more features as desired

Please let us know if this is ok.

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam We understand. Our expectation is the count will be automatically controlled by the result set. It should not be designed to only support 1000 features. As you mentioned you can increase the limit on the user side. We want our users to control this and not the app. I believe we are on the same page. Please proceeed

**Comment by lindsayking** [comment]
http://50.18.115.76/SiteSelector2.3/ has been stood up with the latest version, reflecting the changes discussed above.

**Comment by lindsayking** [comment]
@LindsayThomas   This looks good to me using the state config.  Look good for local?
