### ISSUE TITLE
IE 10 only: Property Information drop-down the Traffic Count Profile text is distorted. However, if you click the arrow the text looks fine. 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#171]
![ie10](https://cloud.githubusercontent.com/assets/2379312/8255648/6e6009de-166f-11e5-8c37-b06eeedd85f4.png)
Property Information drop-down the Traffic Count Profile text is distorted. However, if you click the arrow the text looks fine.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Has this issue been addressed?

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We are unable to reproduce this issue. Is it consistently reproducible at your end? Can you please post a screenshot of the About Internet Explorer dialog, so we can take a look at the exact version of IE.

**Comment by lindsayking** [comment]
@CTLocalGovTeam 

@HeatherEisan and I tested on our end and we are also unable to reproduce this issue.  I'm am closing the issue.
