### ISSUE TITLE
Searching for Maryland, MD in the communities tab does not give any results

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#172]
Searching for Maryland, MD in the communities tab does not give any results.

current version and July version of application
searching for smaller counties work

**Comment by lindsayking** [comment]
The following counties also have the same problem:
* Dorchester
* Somerset
* Talbot

This is only the case of these counties are searched using the textbox input, not the community drop-down.

**Comment by lindsayking** [comment]
Related to #177 

This issue does not appear to be related to our data.  Since it only occurs when a search is performed using the text box, and not the community drop-down, it might be a problem with the geoenrichment service.
