### ISSUE TITLE
Support on phone devices

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#176]
From a conversation with @busbus:

The Site Selector app is not currently supported on phone devices.  But, with a few small changes it might work nicely on the phone.  Support for phone devices might not be essential for the Site Selector app, but it might be important for other configurations, such as the Comp Finder.

Right now, these appear to be the biggest problems we would need to address on the phone:

1)  The basemap switcher.  While we have it hidden on the phone for other apps, it does display for the Site Selector app, and it displays on top of other elements:

![siteselectorbasemapswitcheronphone](https://cloud.githubusercontent.com/assets/4316336/9016559/dbf42218-3786-11e5-8fc2-860e730741c8.png)

----------------------------------------------------

2) The splash screen formatting.  Only the top portion of the window is scrollable, while the rest is empty white space.

![siteselectorsplashscreenonphone](https://cloud.githubusercontent.com/assets/4316336/9016585/093d3d9a-3787-11e5-8a26-571de6304a0a.png)

----------------------------------------------------

3)  In landscape mode, the app shows a mix of both the map and the panels.  It should be either full map display or full screen panel display (like the locator apps).
![siteselectorlandscapephonedevice](https://cloud.githubusercontent.com/assets/4316336/9016596/23dc6efa-3787-11e5-9f50-253cd512a3b6.png)

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
Addressing the first two items seems straightforward, however we have following queries for the third item.

1. **Size change:** When we change the panel to occupy 100% of the screen, the size of images and fonts will remain unchanged, unlike our other responsive apps. Please confirm.
2. **Navigation:** When a panel is open, the only way to close it is by clicking the main icon in top bar (toggle). There wont be any navigation buttons (back, map etc.) to switch between map view and panel view like our other responsive apps. Please confirm.

In case, you want us to implement size change and navigation features, this will be a major development effort. Please suggest.

**Comment by NikkiGolding** [comment]
@ScottOppmann We should discuss.

**Comment by ScottOppmann** [comment]
@CTLocalGovTeam - 

Size Change: We understand images will not resize.  We will leave images as-is in this release.

Navigation: Assume you mean, click on "search" icon to open and close the panel?  If so, that is an acceptable approach.

**Comment by NikkiGolding** [comment]
@lindsayking have we evaluated this behavior in the current drop?

**Comment by lindsayking** [comment]
@NikkiGolding  -  Looking at the current drop on my Android phone, I see that the basemap switcher is no longer present (addressing number 1 in the first comment above), but the splash screen text still only takes up half of the window and the app is half map/half panel in landscape mode (numbers 2 and 3 above).  

So referencing the numbered behaviors in the first comment: #1 is fixed, #2 and #3 are still issues.

**Comment by lindsayking** [comment]
Tested well on Android phone.  None of the above issues are still present.

**Comment by NikkiGolding** [comment]
@lindsayking All looks good on an iPhone too.
