### ISSUE TITLE
Sorting behavior for buildings and sites

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#183]
@CTLocalGovTeam  -  The sorting behavior using Name on the Buildings and Sites tabs does not work correctly.

Steps to repro:
1) Lauch http://tryitlive.arcgis.com/siteselector/ and click ok on the splash screen
2) On the buildings tab, search using the default address and a buffer of at least 5 miles.
3) Sort the search results by name
4) Note that the results are not correctly sorted.  For example, "3342 Bladensburg" is listed below "10120 Bacon Drive", even though 3342 is less than 10120 and should be listed before it.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
The sort behavior you see is correct. '3342 Bladensburg' should be listed below '10120 Bacon Drive' since the complete text is sorted at once. You can copy these texts and sort them in excel to quickly compare the results.

**Comment by lindsayking** [comment]
@NikkiGolding @ScottOppmann @LindsayThomas 

It is true that when these addresses are put in excel and sorted, they are sorted in the same order as they are currently sorted in the Site Selector app.
![image](https://cloud.githubusercontent.com/assets/4316336/10741107/3e8b8cf4-7be3-11e5-9b20-5f85faffd277.png)

**Comment by NikkiGolding** [comment]
@lindsayking this should be easy enough for you to test. Please test. If behavior is consistent, please close the issue.

**Comment by lindsayking** [comment]
Tested.  Sorting is the same between the app and Excel.
