### ISSUE TITLE
Download report menu should expand to display all available reports

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#194]
On touch devices, the report drop-down menu should automatically expand to display all reports.  

Currently, when the application is configured with 3 or more report options (e.g. as is the case with [this app](http://50.18.115.76/SiteSelectorLG/)  ), the report drop-down menu does not automatically expand to display all reports.  

On iPad, the bottom report is completely hidden and there is no visual indicator that the menu can be scrolled to display the third report.

On Android phone, the bottom report is partially obscured.
![image](https://cloud.githubusercontent.com/assets/4316336/11376614/89406534-9296-11e5-96c8-79b2749b0bf4.png)

**Comment by CTLocalGovTeam** [comment]
We will provide the fix in next release.

**Comment by lindsayking** [comment]
Verified with v1.9.  Download drop-down now expands to display 3 or more reports.
![screenshot_2015-12-16-14-28-17](https://cloud.githubusercontent.com/assets/4316336/11855880/c498719a-a401-11e5-803d-2f5e40d4b048.png)
