### ISSUE TITLE
On iOS, if filter portion of panel is partially obscured, radio buttons do not reflect filter choices

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#195]
This behavior only exists on iOS devices: iPad and iPhone.

After a search is executed, if the filter portion of the panel is partially obscured/off-screen, then tapping to turn on/off different radio buttons in the filter options appears to have no effect until the entire panel is visible.

Steps to repro:
1) On an iPad or iPhone, launch http://50.18.115.76/SiteSelectorLG
2) Tap on the Sites tab and execute a search using the default search address and a buffer of 3 or more miles
3) Once the results list is returned, scroll down on the right panel so that at least part of the filters portion of the panel has scrolled off-screen.
4) Tap on or off filter radio buttons on the right panel.  Note that the radio buttons do not reflect user taps until the panel is scrolled to make the entire filter portion of the panel is visible.

This behavior has also been observed through a slightly different workflow:
1) Execute a search that returns no results (e.g. on the Sites tab, search using address '5 N Main Street, Naperville" with a buffer of 12 miles, then select 'Commercial c-1 zone' radio button filter).
2) Click filter
3) No results found
4) Now try to select/unselect radio buttons.  Selection changes are not reflected until the user scrolls to the top of the page.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Do you have any comment on this issue?  Were you able to reproduce?

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide the fix in next release.

**Comment by lindsayking** [comment]
Verified with V1.9 on iPad and iPhone.
