### ISSUE TITLE
After sharing, incorrect Site is reflected in shared version if filter was applied 

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#199]
Steps to repro:
1) Launch http://50.18.115.76/SiteSelectorSG/ and click OK on the splash screen 
2) Click on the Sites tab and search with the default address and a buffer of 6 miles
3) Turn on the Office filter and click Apply Filter
4) Note that there are two results in the results set.  Click on the second one (Capital Office Park - Phase II) to view more information for it.
5) Share the application through Twitter
6) Open the shared version of the application.  Note the application opens to the other Site (Capital Office Park - Lots J/K/L).

This only seems to be reproducible on the Sites tab.

NOTE:  This is not reproducible with the [currently released version](http://tryitlive.arcgis.com/SiteSelector/).

**Comment by lindsayking** [comment]
Additional repro case:
1) Launch http://50.18.115.76/SiteSelectorLG and click OK on the splash screen
2) Click on the Sites tab and search with the default address and a buffer of 8 miles
3) Turn on the "Water Service" and "Gas Service" filters and click Apply Filter
4) Select Celebration Industrial Park from the results set
5) Share the app via twitter
6) Open the shared app.  Note the application opens to a different site.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Do you have any comment on this issue?

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide the fix in next release.

**Comment by lindsayking** [comment]
Verified with V1.9.
