### ISSUE TITLE
Community information does not load when shared for communities with space in name

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#200]
Steps to repro:
1) Launch http://50.18.115.76/SiteSelectorSG and click OK on the splash screen
2) Click on the Communities tab
3) Turn on the radio button to "Search Communities in ..."
4) Choose 'Anne Arundel' or 'Baltimore City' from Community drop-down menu
5) Share the application
6) Open the shared link and note that the application mostly loads, but the geoenriched community information never loads.  Instead, the application spins indefinitely.  Note, this behavior is only reproducible with certain communities.  Others, such as Calvert, Carroll and Frederick are fine.

This is does NOT exist in the currently-released version.  Could it be at all related to our switch from the [abbreviated community name](http://tryitlive.arcgis.com/arcgis/rest/services/SiteSelector/MapServer/2) to [full county names](http://tryitlive.arcgis.com/arcgis/rest/services/SiteSelectorCountyNames/MapServer/2)? It is likely related to there being a space in the community name.  Communities that have a space in the name have this issue, and those that don't are fine.

**Comment by lindsayking** [comment]
Related to the fix made for https://github.com/Esri/site-selector/issues/159.

**Comment by CTLocalGovTeam** [comment]
@lindsayking, 
Correct. This issue is occurring because there is a space in the community names. The names in shared link were not being properly decoded. This is a minor fix.

**Comment by lindsayking** [comment]
Verified with V1.9.  Separate issue created for communities with apostrophes in the name: https://github.com/Esri/site-selector/issues/207.
