### ISSUE TITLE
IE9: Community drop-down menu is missing from Communities tab

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#202]
In IE9 only, the Community drop down menu is not visible on the Communities tab.

To repro:
1) Launch http://50.18.115.76/SiteSelectorSG and click OK on the splash screen
2) Click on the Communities tab
3) Note that the drop-down menu accompanying the second option to "Select communities in ..." is not visible.

It is, however, visible in the currently-released version.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
This appears to be a proxy configuration error. Can you please confirm if proxy is configured correctly. Please see screenshot.

![image](https://cloud.githubusercontent.com/assets/2959186/11471014/37933f4e-9788-11e5-870d-6eaeabd0ab6b.png)

**Comment by lindsayking** [comment]
@CTLocalGovTeam   We fixed the proxy.config and are no longer seeing this issue.  Thanks.
