### ISSUE TITLE
IE9: Results set does not display for Buildings or Sites

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#203]
The search results do not display in IE9 on the Buildings or Sites tabs.

To repro:
1) Launch http://50.18.115.76/SiteSelectorSG and click OK on the splash screen
2) On the Buildings or Sites tabs, search using the default address and a buffer distance of 2 or more miles
3) Note that the 'Filters' section of the panel does not display and no search results are presented.

![image](https://cloud.githubusercontent.com/assets/4316336/11404693/20e3d36e-9358-11e5-9844-22030ae59040.png)

This is a new issue.  We do not see this behavior with the [released version](http://tryitlive.arcgis.com/SiteSelector).  The underlying data for buildings and sites are the same for both the current and released versions though.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
We are seeing proxy configuration errors. Can you please confirm if proxy is configured correctly. Please see screenshot.

![image](https://cloud.githubusercontent.com/assets/2959186/11471089/c3cdfa9e-9788-11e5-8118-fef782a894b8.png)

**Comment by lindsayking** [comment]
@CTLocalGovTeam   We fixed the proxy.config and are no longer seeing this issue.  Thanks.
