### ISSUE TITLE
IE9: Point symbols do not persist on the map when switching between tabs

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#204]
In IE9, if the user performs a search on the Buildings or Sites tab, and then clicks to another tab, then back to the original tab where the search took place, the point features for buildings or sites are no longer visible on the map.

Steps to repro:
1) In IE9, launch http://50.18.115.76/SiteSelectorSG and click OK on the splash screen
2) On the Buildings or Sites tab, perform a search.  Note that only buildings features display on the buildings tab and only sites features display on the sites tab.
3) Click on the Business tab
4) Click back onto the Buildings or Sites tab (whichever tab where the search was performed).  Note that the buildings or sites point features are no longer visible on the map.

This is a new issue introduced in the current version.  It was not present in the [released version](http://tryitlive.arcgis.com/SiteSelector/).

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
This issue is related to proxy configuration as illustrated in issue #202 and #203.
This will get resolved after configuring the proxy correctly.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   We fixed the proxy.config and are no longer seeing this issue.  Thanks.
