### ISSUE TITLE
Site Selector pop-up needs to honor webmap pop-up media options 

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/site-selector#208]
![12-17-2015 2-13-59 pm](https://cloud.githubusercontent.com/assets/5614261/11883528/77cca256-a4c8-11e5-8d6d-3c76bba735e3.png)

**Comment by kbusby** [comment]
Thanks Chris, 
Anything I can help with let me know. I am also having issues with obtaining a token with this app if you happen to know what I may have wrong.
