### ISSUE TITLE
Point config.js and proxy to  try it live webmap id and services

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#210]
Point config.js and proxy to try it live webmap id and services
- [x] config.js updated to reflect the tryitlive version of the application
- [x] proxy file references to dev server removed

**Comment by lindsayking** [comment]
@LindsayThomas 

* configLG.js - no changes needed.  Already matched TIL version
* config.js - updated to match TIL version (version with attachments)
* proxy.config - no changes needed.  Already matched shipped version with no references to dev server.
