### ISSUE TITLE
Facebook share text is hard coded as "Site Selector ..."

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#215]
The text that displays when the app is shared through Facebook always displays as "Site Selector ...".  This should be configurable to reflect other application names or text that customers may want to use.

If the FacebookShareURL parameter in the config.js is updated as shown below
<code>FacebookShareURL: "http://www.facebook.com/sharer.php?u=${0}&t=Residential%20Comp%20Finder",</code>, the URL that displays in the address bar when sharing to facebook correctly reflects this value ("https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fbit.ly%2F1NQVmti&t=Residential+Comp+Finder"), but the text that displays on the facebook page remains the same:

![image](https://cloud.githubusercontent.com/assets/4316336/12801119/e356d6d6-ca8e-11e5-98d4-bc3d2fcb9fdb.png)

This is not an issue with sharing via Twitter.

**Comment by LindsayThomas** [comment]
@ChrisBuscaglia @lindsayking If you create another default.htm for  Comp Finder and update line 23 here: https://github.com/Esri/site-selector/blob/69406924af8364590e3313c0b14465878f58dc20/default.htm
then this will fix the sharing issue. 

The title in the default.htm should come from the localized string in the longer term
