### ISSUE TITLE
Add ability to set the search location by clicking on the map

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#219]
Add the ability to allow users to set the search location by clicking on the map.
- This enhancement has specifically been requested by a consultant of Esri Portugal.  Since we've added this enhancement in the latest release of the configurable locator, it would be nice to include it in Site Selector as well.

**Comment by lindsayking** [comment]
Jeremiah has reported that City of Phoenix also mentioned it would be nice to have this ability.

**Comment by ChrisBuscaglia** [comment]
Trying to see if the City of Phoenix is using the app - can't find it on their econ. dev. site or mapping portal.
