### ISSUE TITLE
Disable Geolocation by commenting it out in the config.js for all Configurations

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#220]
Add Comment... 
The geolocation button has been hidden from the user interface by commenting out the widgetpath for geolocation below. You can enable geolocation by uncommenting the widgetpath for geolocation. The geolocation button, however, will only work on browsers supporting geolocation over HTTP connections.  If a browser requires a HTTPS connection to support geolocation and the button is enabled, the button will not work, but the application will work correctly otherwise.

//{
    // WidgetPath: Widgets/geoLocation/geoLocation"
    // },

**Comment by LindsayThomas** [comment]
@lindsayking please do this

**Comment by LindsayThomas** [comment]
@lindsayking This has been committed . Please verify when you test before shipping

**Comment by lindsayking** [comment]
Verified.
