### ISSUE TITLE
Large photos are rotated from portrait to landscape mode 

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#222]
When large photos with a portrait orientation are added as attachments and displayed in the Site Selector application, they are rotated in the app and display in landscape mode.  

This only appears to be the case for large photos (e.g. 2448 x 3264 pixels).  When the same photos are resized to be smaller, the application no longer displays them rotated.  Also, large photos with landscape orientation are not rotated; they remain correctly in landscape mode.

Note, when the same photos are opened from the popup in the ArcGIS Online map viewer, they display correctly (not rotated).

Issue reported by Jer.

**Comment by ChrisBuscaglia** [comment]
@lindsayking I can't find Jeremiah on Github - was this reported by a customer he was working with, if so, can you please send him my way?

**Comment by ChrisBuscaglia** [comment]
@lindsayking Nevermin - found it.
