### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by Carolinercraig** [Esri/site-selector#223]
Hi, I downloaded the sourcecode and tried running it, but got the Unexcpected token error whenever I click the result item to go to the information page.

Also upon loading the app, it throws the error _The searched area is outside the area of interest and will not be analyzed. In the browser console tab it says: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://tasks.arcgisonline.com/ArcGIS/rest/info?f=json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

I tried installing COR extension to my chrome browser but this gave my browser other issues.

Please help with these issues I am facing.

**Comment by lindsayking** [comment]
@Carolinercraig 

Regarding the Unexpected token error, I have a couple of questions for you.
* Have you registered your application with your ArcGIS Online organizational account and entered the resulting App ID and App Secret into the clientId and clientSecret (respectively) settings in the app's proxy.config?  Here's [help](http://solutions.arcgis.com/state-government/help/site-selector/get-started/configure-proxy/) if needed.
* Are you still running into this issue now?  The GeoEnrichment service that is used by the Site Selector app recently updated, which may have fixed the issue.

Regarding the "searched area is outside the area of interest and will not be analyzed" behavior:
* This message appears if the area being searched is outside of the default extent of the web map used by the app.  Try to make sure your web map's default extent includes the entire area you want to be searchable.
* Another thing to check would be to make sure the data frame was in Web Mercator Auxiliary Sphere (WKID 102100/3857) when you published the service(s) you are using in your Site Selector web map.

I hope this helps. Let me know how things go.

**Comment by Carolinercraig** [comment]
Hi,

Thanks for you response, I initially had thought that using the sample code
downloaded would have showed me what I am seeing online. I have not touched
the code after downloaded. All I had wanted to see, is the sample working
on my local computer.

Kindly let me know your thoughts,
Thanks,
Caroline

**Comment by lindsayking** [comment]
@Carolinercraig 

There are a couple of steps that you will need to take to get the sample code working on your computer.  The help documentation should walk you through it.  Here are the key steps:
- [Configure your proxy](http://solutions.arcgis.com/state-government/help/site-selector/get-started/configure-proxy/)  (even if you are using the sample webmap and make no changes to the application's configuration, you will need to do this step because the application uses the GeoEnrichment service).
- [Publish the application](http://solutions.arcgis.com/state-government/help/site-selector/get-started/publish-application/)

Once you get through these steps, you should be up and running with the app.  You may, however, still run into the message that says the "searched area is outside the area of interest and will not be analyzed".  That is related to https://github.com/Esri/site-selector/issues/225 and we are actively working with Technical Support to address the issue.

**Comment by Carolinercraig** [comment]
Hi,

Thanks for the information. I followed the steps, and I published, and I
have passed the issue. I tested the site
http://190.197.42.59/realestate/default.htm, but as I click the list item
to view the item detail, I am meeted with this error: XMLHttpRequest cannot
load http://tasks.arcgisonline.com/ArcGIS/rest/info?f=json. No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://190.197.42.59' is therefore not allowed access.

I am not sure what I am missing. I did believe I added the correct services
config to my proxy file...attached is my files.

Thanks in advance for all your help.

thanks,
Caroline

**Comment by lindsayking** [comment]
@Carolinercraig 

I'm glad to hear you've gotten past the initial issues you were seeing.  

Based on your latest comment, it looks to me like there still might be an issue with how your proxy.config is configured.  You want to make sure you reference all of the services being used in the app, and you need to be sure to provide a clientID and a clientSecret for the geoenrichment service.

Have you added and registered your application (help is mid-way down [this page](http://solutions.arcgis.com/state-government/help/site-selector/get-started/configure-proxy/)) on ArcGIS Online?  If so, make sure you've plugged the AppID and AppSecret from that registered application item on ArcGIS Online into the clientId and clientSecret parameteres in the proxy.config (respectively). 

```
<serverUrls>
        <serverUrl url="http://tryitlive.arcgis.com/arcgis/rest/services/" matchAll="true"></serverUrl>
        <serverUrl url="http://arcgis4localgov2.maps.arcgis.com" matchAll="true"></serverUrl>
        <serverUrl url="http://tasks.arcgisonline.com/ArcGIS/rest/" matchAll="true"></serverUrl>
        <serverUrl url="http://www.arcgis.com/sharing/rest/" matchAll="true"></serverUrl>
        <serverUrl url="http://services.arcgis.com/8KEQHzVdm3qDSW1h/arcgis/rest/" matchAll="true"></serverUrl>
        <serverUrl url="http://services6.arcgis.com/Pu6Fai10JE2L2xUd/" matchAll="true"></serverUrl>
        <serverUrl url="http://services.arcgis.com/doC3DvW5p9jGtDST/arcgis/rest/" matchAll="true"></serverUrl>
        <serverUrl url="http://52.26.253.224:6080/arcgis/rest/" matchAll="true"></serverUrl>
        <serverUrl url="http://geocode.arcgis.com/arcgis/rest/services/" matchAll="true"></serverUrl>
        <serverUrl url="http://geoenrich.arcgis.com/arcgis/rest/"
	         clientId="<app ID from registered item on ArcGIS Online>"
	         clientSecret="<app Secret from registered item on ArcGIS Online>"
	         matchAll="true"
	         rateLimit="1000"
             rateLimitPeriod="10">
        </serverUrl>
        <serverUrl url="https://api-ssl.bitly.com/v3/shorten"
           matchAll="true"
           accessToken="09392d98805bea10e1a1ad5c8fd206b43985c6c0"
           tokenParamName="access_token"
           rateLimit="50"
           rateLimitPeriod="10">
        </serverUrl>
```

I'm hoping that does the trick.  Let me know.

**Comment by kbenard7** [comment]
Hello @lindsayking @Carolinercraig @EsriGithub @ajturner @asizer , I'm also getting the same error"unexpected tolen" while trying to edit the service url and title of a feature service in a mapping portal that has current subscription. Do you have any idea what this problem is and how I can fix it?

**Comment by lindsayking** [comment]
@kbenard7 -  Can you provide a little more information on your environment and the steps you are following?  Is it something you are encountering when standing up the site-selector app?

**Comment by kbenard7** [comment]
Hello Lindsay,


Thanks for finding time out of your busy schedule to help me out

We are using  Portal for ArcGIS version 10.3 which is federated with ArcGIS
Server. The ArcGIS Server is also version 10.3.



The error was persistent in both Chrome and Internet Explorer.


I'm receiving a token error when attempting to modify the Item Details page
of a feature service.




Find the attached screenshot of the error. This error occurred when I
clicked on the “save” icon.


Thanks again for your time,

Benard Kirui | +254736161022
GIS& Remote Sensing Specialist

**Comment by ChrisBuscaglia** [comment]
@kbenard7 Can you please open a tech support issue regarding the problem that you are encountering?

Thanks

Chris

**Comment by kbenard7** [comment]
Hello Chris,

Thanks for the  advice.  I have already solved the issue.  The token
generated was specific to Google Chrome version 54 and Firefox version 49.
Thanks,
Ben

**Comment by ChrisBuscaglia** [comment]
@kbenard7 Thanks, closing issue.
