### ISSUE TITLE
Update Residential Comp Finder to use TryItLive organizations basemap group instead of states

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#230]
Go to: https://github.com/Esri/site-selector/blob/master/js/configCompFinder.js#L86 notice the basemap group and user being used is from the State Model Org instead of the LocalGov Try it Live Org. 

We should update it to our tryitlive org

**Comment by ChrisBuscaglia** [comment]
Updated a37e19138fd53c777b950a079508e0aa7b981be1

**Comment by ChrisBuscaglia** [comment]
Leave a comment
