### ISSUE TITLE
JS 4.x version?

### ISSUE THREAD

**Issue by dbutz** [Esri/site-selector#232]
Hi, I am looking to update my own JS app to 4.x and I was looking for a sample with a great UI that I could derive from.

I really like this app's look and feel but I wanted to start out with it already written in 4.x. Do you know when you might release an updated version?

**Comment by LindsayThomas** [comment]
@dbutz  We don't have any plans on updating this application to use JS 4.X as we just moving it to mature support with our April 2018 release. It has been replaced by the Near Me Widget in Web AppBuilder for ArcGIS, however that is using the 3.x API as well.
