### ISSUE TITLE
Buildings and Sites - "No results found" when sorting by empty field

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#98]
@CTLocalGovTeam  When the search results are sorted on a field that is empty, a "No results found" message displays and the results disappear from the infopanel.  

Using http://203.199.47.146/EconDevSiteFinder_v1.2/ as an example, search on the Buildings tab using the default search address and a buffer of 10 miles or more. Then sort the results by "County".  Note the "No results found" message and that the search results are no longer visible.

Instead, the message that displays should be more informative, and the results should remain as they are in the infopanel.

**Comment by LindsayThomas** [comment]
As Designed. Cannot sort on empty field
