### ISSUE TITLE
Selected feature does not always persist in shared version

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#99]
@CTLocalGovTeam 

When a building or site feature is selected from the search results, it is highlighted on the map and its details display in the info panel.  But when the app is shared, the feature selection does not always persist in the shared version.

1) Perform a search on the buildings or sites tab
2) Select a result from the search result
3) Note the highlighted feature on the map and the feature attributes on the info panel.
4) Share the app
5) Open the shared version of the app.  Note the feature in the shared version is not always the same as in the original (both on the map and the info panel).

This behavior seems to manifest after two or three searches on the same tab.

Similar issue: https://github.com/Esri/site-selector/issues/79

**Comment by LindsayThomas** [comment]
SG (search 3 or 4 times on same tab and get the same results sharing.)
